### ISSUE TITLE
XML runner doesn't report failures correctly.

### ISSUE THREAD

**Issue by alexcouper** [Gagnavarslan/sst#9]
If you use the xml runner, you'll never get errors returned the calling function.

https://github.com/kamyanskiy/sst/blob/master/src/sst/runtests.py#L102

The result class used in this case is encapsulates methods for sending errors to the test cases, but does not ask for their failures or errors during the return statement

```
len(result.failures) + len(result.errors)
```

Class is here: https://github.com/testing-cabal/testtools/blob/master/testtools/testresult/real.py#L796

**Comment by arnlaugsson** [comment]
This should be fixed with #17 - correct @romank0 ?

**Comment by romank0** [comment]
yes
